local_costmap:
  global_frame: world
  robot_base_frame: bebop
  update_frequency: 2.0
  publish_frequency: 1.0
  static_map: false
  rolling_window: true
  width: 10.0
  height: 10.0
  resolution: 0.025
  origin_x: 0.0
  origin_y: 0.0